import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";
import { isAuthenticated } from "@/utils/actions";
import UserContext from "./UserContext";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Atom",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const userResponse = await isAuthenticated(true);

  // const currentUser =
  //   userResponse &&
  //   userResponse.id &&
  //   userResponse.username &&
  //   userResponse.displayname &&
  //   userResponse.description &&
  //   userResponse.avatar_url
  //     ? {
  //         id: userResponse.id,
  //         username: userResponse.username,
  //         displayname: userResponse.displayname,
  //         description: userResponse.description,
  //         avatar_url: userResponse.avatar_url,
  //       }
  //     : null;

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased dark",
          fontSans.variable
        )}
      >
        <UserContext>
          <Providers>
            <Navbar />

            {children}
          </Providers>
        </UserContext>
      </body>
    </html>
  );
}
